// Completion is announced once per attempt. Optional dismantling never reopens the battle.
let clearNoticeShown=false,clearAction=null,clearPauseOwned=false,clearDialogsEnabled=true;
function levelRule(n){if(n===1)return '拆除 3 处压力话语，各打掉 40%';const total=GAME_CONFIG.waves[n].reduce((a,b)=>a+b,0);return '击败 '+total+' 只小怪'+(n===5?'，再击败最终 Boss':'')}
function resetClearFlow(){clearNoticeShown=false;clearAction=null;clearPauseOwned=false;$('#clear-dialog').hidden=true;$('#clear-screen').hidden=true}
function showClearIfReady(){if(!clearDialogsEnabled||!growth?.complete||clearNoticeShown||choiceNode||ending||settled)return;clearNoticeShown=true;closeGameSheets();clearPauseOwned=!paused;paused=true;clearHeldInput();$('#paused').style.display='none';$('#clear-screen').hidden=false;$('#clear-dialog').hidden=false;$('#clear-title').textContent=level===5?'五关挑战完成！':'第 '+level+' 关通关！';$('#clear-condition').textContent='✓ '+levelRule(level)+' · 已全部完成';$('#clear-detail').textContent=level===1?'三处话语已拆除。':waves.killed+' / '+waves.total+' 只小怪已击败，刷新已停止。'+(level===5?'最终 Boss 已击败。':'');const pending=pendingNodes().length;$('#clear-upgrades').textContent=pending?'还有 '+pending+' 次升级可领取；选择后会随装备继承。':'当前装备将在结算后继承到下一关。';$('#clear-next').hidden=level===5;$('#clear-next').textContent='进入第 '+(level+1)+' 关';$('#clear-end').textContent=level===5?'查看通关成绩':'结算这一关';$('#clear-next').hidden?$('#clear-end').focus({preventScroll:true}):$('#clear-next').focus({preventScroll:true});renderMusic()}
function dismissClear(){const owned=clearPauseOwned;clearPauseOwned=false;$('#clear-dialog').hidden=true;$('#clear-screen').hidden=true;if(owned&&paused&&!choiceNode&&!ending&&!settled)paused=false;clearHeldInput();$('#paused').style.display=paused?'grid':'none'}
function continueAfterClear(){dismissClear();if(!choiceNode&&!ending&&!settled)paused=false;clearAction=null;growth.continued=true;renderGrowth();unlockAudio();focusGame()}
function nextAfterClear(){if(!growth.complete||level>=5||growth.committed)return;dismissClear();clearAction='next';requestEnd()}
function endAfterClear(){dismissClear();clearAction=null;requestEnd()}
function renderClearStandards(){if(!growth)return;$('#battle-rule').textContent='通关标准：'+levelRule(level);$('#battle-summary').textContent=growth.complete?'✓ 已通关':level===1?'目标 '+targets.filter(t=>t.done).length+' / 3':(waves.ended?'小怪清空':`第 ${Math.min(waves.index+1,GAME_CONFIG.waves[level].length)} / ${GAME_CONFIG.waves[level].length} 波`)+` · 已击败 ${waves.killed} / ${waves.total}`;$('#battle-remaining').textContent=level===1?(growth.complete?'目标已完成':'还剩 '+targets.filter(t=>!t.done).length+' 处'):growth.complete?'停止刷新':waves.ended?(level===5?'Boss 剩余 '+Math.ceil(boss.hp)+' / '+boss.maxHp:'停止刷新'):'还剩 '+(waves.total-waves.killed)+' 只（场上 '+waveAlive().length+'，待出现 '+(waves.total-waves.spawned)+'）';$('#quick-next').hidden=!growth.complete||level===5||ending||settled;$('#quick-next').textContent='进入第 '+(level+1)+' 关';$('#quick-finish').textContent=level===5?'通关成绩':'结算';$('#battle-strip').classList.toggle('cleared',growth.complete);if(!$('#all-level-rules').children.length)for(let n=1;n<=5;n++){const row=document.createElement('li');row.textContent='第 '+n+' 关：'+levelRule(n);row.classList.toggle('current',n===level);$('#all-level-rules').append(row)}showClearIfReady()}
$('#clear-next').onclick=nextAfterClear;$('#clear-continue').onclick=continueAfterClear;$('#clear-end').onclick=endAfterClear;$('#quick-next').onclick=nextAfterClear;
