musicEnabled=false;muted=true;const rows=[];function check(name,pass,data){rows.push({name,pass:!!pass,data})}function fresh(){resetGame();begin();time=0;muted=true;for(const t of targets)t.nextSpawn=1e6}function drain(){while(pendingNodes().length){if(!choiceNode)openUpgrade();claimUpgrade(openChoices[0])}}
function arena(){fresh();for(const a of all)destroy(a,a.x,a.y);progress();drain();activateBoss();Object.assign(boss,{x:620,y:H-450,nextAttack:0});Object.assign(p,{x:450,y:boss.y+boss.h*.72+24,face:1});pointer.moved=false;invincibleUntil=1e6;mods={A:4,B:0,C:4,D:3}}
fresh();let xy={x:p.x,y:p.y};$('#boss-guide').click();updateBoss(.01);check('Locate does not teleport or summon',!boss.active&&p.x===xy.x&&p.y===xy.y);let a=bossAnchor();p.x=a.x;p.y=a.y;updateBoss(.01);check('Large boss appears on approach',boss.active&&boss.w===260&&boss.h===400&&boss.hp===3600);check('Large boss is over ten times player height',boss.h/p.h>10);check('Geometry includes multiple body parts',shapeParts(boss).length>=10);check('No rectangle collision in empty upper corner',actorSegment(boss.x,boss.y,boss.x+20,boss.y+10,boss)===null);check('Visible head has hit geometry',actorSegment(boss.x,boss.y+64,boss.x+260,boss.y+64,boss)!==null);check('Space between lower legs is not an air wall',actorSegment(boss.x+129,boss.y+360,boss.x+132,boss.y+360,boss)===null);check('Boss participates in shared candidate list',combatCandidates(boss.x,boss.y,boss.w,boss.h).includes(boss));
for(const [label,x,y] of [['head',130,64],['torso',130,200],['left hand',35,291],['right hand',226,288],['left leg',95,340],['right shoe',170,390]]){arena();let point={x:boss.x+x,y:boss.y+y};check('Visible '+label+' is hittable',actorSegment(point.x-500,point.y,point.x,point.y,boss)!==null);let hp=boss.hp;impact(point.x,point.y);check('Blast damages '+label,boss.hp===hp-getWeaponStats().grenadeDamage*combatConfig.boss.explosionMultiplier)}
for(const w of [0,1,2]){arena();mods.B=0;Object.assign(p,{x:boss.x-55,y:boss.y+291+24,face:1});selectWeapon(w);const hp=boss.hp;fire();for(let i=0;i<25;i++)updateBullets(1/60);check('Actual weapon '+(w+1)+' hits rendered figure',boss.hp<hp,{hpBefore:hp,hpAfter:boss.hp})}
arena();const nullX=boss.x+3,nullY=boss.y+5;mods.C=0;impact(nullX,nullY);check('Explosion in bounding-box corner respects silhouette',boss.hp===3600-getWeaponStats().grenadeDamage*combatConfig.boss.explosionMultiplier||boss.hp===3600,{hp:boss.hp});
for(const [phase,hp] of [[1,3600],[2,1900],[3,800]]){arena();boss.hp=hp;updateBoss(.01);check('Phase '+phase+' has actual prefire warning',boss.phase===phase&&!!boss.warning&&enemyShots.length===0);let w={...boss.warning};const spec=combatConfig.boss.phases[phase-1];time=spec.warning-.001;updateBoss(.01);check('Phase '+phase+' respects warning duration',enemyShots.length===0);p.x=boss.x+boss.w+220;time+=.003;updateBoss(.01);check('Phase '+phase+' fan locks announced direction',enemyShots.length===spec.fan&&enemyShots.every(b=>b.vx<0),{count:enemyShots.length});check('Shots originate from announced hand',enemyShots.every(b=>Math.abs(b.x-(boss.x-3))<.01));for(let i=0;i<300;i++)updateEnemyShots(1/60);check('Phase '+phase+' bullets expire',enemyShots.length===0);}
arena();boss.hp=800;boss.cycle=2;updateBoss(.01);check('Rush is preannounced',boss.warning?.type==='rush');p.x=boss.x+500;time=.651;updateBoss(.01);check('Rush direction locks before player moves',!!boss.dash&&boss.dash.dx<0);let x=boss.x;time+=.1;updateBoss(.1);check('Large body rush moves in real world',boss.x<x);time+=.7;updateBoss(.1);check('Rush duration bounded',!boss.dash);
arena();boss.hp=1000;invincibleUntil=0;const m=JSON.stringify(mods),g=goneGlyphs;for(let i=0;i<4;i++){time+=1.01;hurtPlayer(p.x-30)}check('Failure heals twelve percent, keeping glyph destruction',boss.hp===1432&&boss.recoveries===1&&goneGlyphs===g&&JSON.stringify(mods)===m);check('Recovery grants protection',invincibleUntil-time>=1.59);
arena();const frozen={time,hp:boss.hp,x:boss.x};paused=true;last=1000;frame(1033);check('Pause freezes giant boss',time===frozen.time&&boss.hp===frozen.hp&&boss.x===frozen.x);
fresh();for(const t of targets)for(const a of t.items)destroy(a,a.x,a.y);progress();drain();check('Sources alone cannot clear fifth',!growth.complete);activateBoss();hurtBoss(3600,0);progress();check('Sources plus boss clears fifth',growth.complete&&growth.sources.boss===500&&!boss.alive&&!objectAlive(boss.id));hurtBoss(10000,0);check('Boss reward is idempotent',growth.sources.boss===500);const q=glyphs.find(a=>a.alive);destroy(q,q.x,q.y);check('Victory allows continued webpage destruction',!q.alive&&!ending);resetGame();check('Retry restores 3600HP boss and glyphs',boss.hp===3600&&!boss.active&&all.every(a=>a.alive));
arena();for(let i=0;i<29;i++)enemyShots.push({source:'boss',x:100,y:H-80,vx:200,vy:0,remaining:760,life:3,text:'？'});boss.warning={at:-10,dx:-1,dy:0,side:-1,type:'fan'};boss.hp=800;boss.phase=3;updateBoss(.01);check('Combined projectile cap is 32',enemyShots.length===32);
const out=document.createElement('pre');out.id='results';out.textContent=JSON.stringify({passed:rows.every(r=>r.pass),count:rows.length,failed:rows.filter(r=>!r.pass),rows},null,2);out.style='position:fixed;inset:0;z-index:90;background:white;overflow:auto';document.body.append(out);paused=true;
