musicEnabled=false;muted=true;const rows=[];function check(name,pass,data){rows.push({name,pass:!!pass,data})}function fresh(){resetGame();begin();time=0;muted=true}function drain(){while(pendingNodes().length){if(!choiceNode)openUpgrade();claimUpgrade(openChoices[0])}}function closeAll(){for(const t of targets)for(const a of t.items)destroy(a,a.x,a.y);progress()}
fresh();check('Five independent music themes',Object.keys(MUSIC_THEMES).length===5&&new Set(Object.values(MUSIC_THEMES).map(t=>t.title)).size===5&&new Set(Object.values(MUSIC_THEMES).map(t=>t.melody.join())).size===5);check('Six through ten upgrade nodes',growth.nodes.length===level+5&&nodeThresholds.length===level+5);check('Every upgrade reachable using actual letters',nodeThresholds.at(-1)<=glyphs.length,{glyphs:glyphs.length,thresholds:nodeThresholds});check('First upgrade requires sustained destruction',nodeThresholds[0]>=70);check('Extended tiers are real values',GAME_CONFIG.upgrades.A.length===13&&GAME_CONFIG.upgrades.D[12]===.52&&maxModLevel===[0,4,6,8,10,12][level]);check('Game task panel is distinct and outside terrain',$('#growth-hud').classList.contains('game-panel')&&!all.some(a=>a.el?.closest('#growth-hud,#hud,#upgrade')));
let oldX=p.x;keys.add('d');for(let i=0;i<20;i++)move(1/60);keys.clear();check('Movement preserved',p.x>oldX+30);let oldY=p.y;doJump();move(1/60);check('Jump preserved',p.y<oldY&&p.vy<0);
fresh();award('enemy',5000);progress();check('Points and enemy kills cannot skip glyph requirements',pendingNodes().length===0&&!paused&&goneGlyphs===0);fresh();closeAll();check('Source completion no longer grants entire upgrade ladder',growth.nodes.some(n=>n.state==='locked')&&goneGlyphs<nodeThresholds.at(-1));
fresh();const clean=glyphs.filter(a=>!a.el.closest('[data-goal]'));for(const a of clean.slice(0,nodeThresholds[0]-1))destroy(a,a.x,a.y);progress();check('No early upgrade before required letters',pendingNodes().length===0&&goneGlyphs===nodeThresholds[0]-1);const a=clean[nodeThresholds[0]-1];destroy(a,a.x,a.y);progress();check('Exact unique-letter milestone opens upgrade',goneGlyphs===nodeThresholds[0]&&choiceNode===growth.nodes[0]&&paused);let count=goneGlyphs;destroy(a,a.x,a.y);check('Destroyed letter cannot farm growth',goneGlyphs===count);const choice=openChoices[0],m=mods[choice];claimUpgrade(choice);check('Upgrade applies and does not force next modal',mods[choice]===m+1&&!choiceNode&&!paused);check('Remaining letters count agrees with next milestone',$('#growth-status').textContent.includes(String(nodeThresholds[1]-goneGlyphs)));
fresh();mods={A:12,B:0,C:0,D:0};const groups=new Map();for(const a of glyphs.filter(a=>a.el.closest('article'))){const key=Math.round(a.y*100);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(a)}const longRow=[...groups.values()].find(r=>r.length>=34&&r[33].x-r[0].x<620)||[...groups.values()].sort((a,b)=>b.length-a.length)[0];const expectedHits=Math.min(34,longRow.length);const first=longRow[0],st=getWeaponStats(),b={x:first.x-3,y:first.y+8,vx:1100,vy:0,remaining:640,life:2,heavy:false,sub:false,hits:0,maxHits:st.pierce,damage:st.damage,hitIds:new Set(),split:{...st.split}};bullets.push(b);for(let i=0;i<50;i++)updateBullets(1/60);check('Tier XII primary piercing respects available row length',b.hits===expectedHits,{hits:b.hits,expectedHits,configuredCap:st.pierce});
fresh();mods={A:0,B:12,C:0,D:0};const g=glyphs.find(a=>a.el.closest('#spawn-paragraph'));const sub={x:g.x-3,y:g.y+8,vx:1100,vy:0,remaining:640,life:2,heavy:false,sub:false,hits:0,maxHits:1,damage:1,hitIds:new Set(),split:{...getWeaponStats().split}};bullets.push(sub);updateBullets(1/60);check('Tier XII splits into 12 independent projectiles',bullets.length===12&&bullets.every(b=>b.sub&&b.maxHits===1&&b.split.count===0&&b.remaining===410),{count:bullets.length});const before=bullets.length;splitAt(bullets[0],g.x,g.y);check('No recursive splitting',bullets.length===before);
fresh();mods={A:0,B:0,C:12,D:12};check('Tier XII blast radius and cooldown',getWeaponStats().radius===250&&getWeaponStats().cooldown===.52);selectWeapon(1);pointer.moved=false;p.x=700;p.y=H-50;fire();bullets=[];time=.519;fire();check('Cooldown still blocks early shots',bullets.length===0);time=.52;fire();check('Shorter cooldown actually releases shot',bullets.length===1);
if(level>=2){fresh();p.x=1150;p.y=targets[0].items[0].y-80;camY=targets[0].items[0].y-200;let found=targets.map(spawnPlace).filter(Boolean)[0];check('Larger monsters can still find real text floor',!!found&&found.w===82&&found.h===52,found);if(found){const e=spawnEnemy(targets[0],'chaser',found);check('Monster size equals actual body collision',e.w===82&&e.h===52);const hp=e.hp;Object.assign(p,{x:e.x-55,y:e.y+20+24,face:1});pointer.moved=false;mods={A:12,B:0,C:0,D:0};selectWeapon(0);fire();for(let i=0;i<20;i++)updateBullets(1/60);check('Normal monster remains damageable after visual enlargement',e.hp<hp,{hpBefore:hp,hpAfter:e.hp})}}
fresh();for(const a of all)destroy(a,a.x,a.y);progress();check('Entire ladder unlocked at full destruction',growth.nodes.every(n=>n.state!=='locked'));drain();check('All six to ten choices can actually be claimed',growth.nodes.every(n=>n.state==='claimed'));if(level===5){activateBoss();hurtBoss(99999,0);progress()}check('Existing source-plus-boss completion rule',growth.complete);const earned=JSON.stringify(mods);requestEnd();check('Settlement succeeds with new growth metric',ending&&!!run.results[level]);check('Cross-level inheritance preserves chosen upgrades',level===5||JSON.stringify(run.entries[level+1])===earned);const result=JSON.stringify(run.results[level]);commitLevel();check('Settlement remains idempotent',JSON.stringify(run.results[level])===result);resetGame();check('Retry restores entry with no glyph farming',goneGlyphs===0&&growth.nodes.every(n=>n.state==='locked')&&all.every(a=>a.alive));
for(const z of [.8,1,1.25]){document.body.style.zoom=z;resize();camY=600;updateTransforms();refreshGeometry();hitDebug=true;draw();check('Stable webpage coordinates after zoom '+z,debugStats.maxWorldError<.001,debugStats.maxWorldError)}document.body.style.zoom='';resize();
check('Task panel can collapse to free the sidebar',!!$('#mission-toggle')&&$('#mission-toggle').getAttribute('aria-expanded')==='true');$('#mission-toggle').click();check('Collapsed panel reports mission and next upgrade',$('#growth-hud').classList.contains('compact')&&$('#compact-task').textContent.includes('下次升级'));$('#mission-toggle').click();
const out=document.createElement('pre');out.id='results';out.textContent=JSON.stringify({passed:rows.every(r=>r.pass),count:rows.length,failed:rows.filter(r=>!r.pass),rows},null,2);out.style='position:fixed;inset:0;z-index:90;background:white;overflow:auto';document.body.append(out);paused=true;
