// Five-level page assault: detached DOM glyphs become finite, physically hit moving actors.
let survival=null;const survivalSettingsCopy=$('#settings-sheet p').innerHTML;
const ASSAULT_PROFILES={
1:{name:'入门',description:'单线预警 · 少量追踪 · 标题回复护盾',advance:34,letterSpeed:160,spawnInterval:.20,maxActive:48,warmup:.45,batch:2,hp:1,strongHp:2,eliteScale:1,elites:1,fan:3,shotSpeed:190,eliteCooldown:4.2,turn:.7,shield:6,invincible:1.4,lanes:1,warning:1.15,casterEvery:0,chargedHp:1,healEvery:1},
2:{name:'轻压',description:'双线封锁 · 交叉文字 · 普通弹可擦除',advance:36,letterSpeed:195,spawnInterval:.18,maxActive:60,warmup:.4,batch:2,hp:2,strongHp:4,eliteScale:1.8,elites:2,fan:3,shotSpeed:225,eliteCooldown:3.5,turn:.9,shield:5,invincible:1.2,lanes:2,warning:1,casterEvery:0,chargedHp:1,healEvery:2},
3:{name:'追击',description:'追踪文字 · 重字弹需多次擦除 · 双线预警',advance:38,letterSpeed:230,spawnInterval:.16,maxActive:64,warmup:.35,batch:2,hp:5,strongHp:8,eliteScale:2.6,elites:2,fan:5,shotSpeed:250,eliteCooldown:3,turn:1.2,shield:5,invincible:1.1,lanes:2,warning:.9,casterEvery:18,chargedHp:3,healEvery:3},
4:{name:'围攻',description:'三线封锁 · 远程文字交火 · 护盾更少',advance:40,letterSpeed:255,spawnInterval:.15,maxActive:68,warmup:.3,batch:2,hp:6,strongHp:10,eliteScale:3.5,elites:3,fan:7,shotSpeed:275,eliteCooldown:2.65,turn:1.5,shield:4,invincible:1,lanes:3,warning:.85,casterEvery:14,chargedHp:4,healEvery:3},
5:{name:'极限',description:'高密度追击 · 重字弹幕 · 三阶段董事长',advance:42,letterSpeed:280,spawnInterval:.14,maxActive:72,warmup:.28,batch:2,hp:8,strongHp:12,eliteScale:4.4,elites:3,fan:7,shotSpeed:285,eliteCooldown:2.3,turn:1.8,shield:5,invincible:.95,lanes:3,warning:.8,casterEvery:11,chargedHp:5,healEvery:2}};
const PAGE_ASSAULT=ASSAULT_PROFILES[level];
function survivalStats(){if(level>=2)return assaultAdvancedStats();const st=getWeaponStats();const equipment=Math.min(12,st.arsenal+mods.C),cooling=Math.min(12,Math.ceil(st.arsenal*.6)+mods.D);return {...st,radius:GAME_CONFIG.upgrades.C[equipment],grenadeDamage:5+Math.floor(equipment*1.5),cooldown:GAME_CONFIG.upgrades.D[cooling],rate:Math.min(12,8+mods.A*.4+mods.B*.25),pierce:Math.min(6,Math.max(2,st.pierce)),fan:Math.min(4,st.split.count),eraserRange:100+st.arsenal*7+mods.C*3,eraserDamage:st.eraserDamage+(sh<500?1:0),eraserCooldown:Math.max(.16,(sh<500?.22:.4)-st.arsenal*.025-mods.D*.025)}}
function survivalBounds(){const inset=playInsets(),left=camX+14/scale,right=camX+(sw-14)/scale,top=camY+(inset.top+12)/scale,bottom=camY+(sh-inset.bottom-12)/scale;return {left,right,top,bottom,width:right-left,height:Math.max(80,bottom-top)}}
function survivalAnchor(){const inset=playInsets();return inset.top+(sh-inset.top-inset.bottom)*.72}
function survivalMinRoute(){return (survivalAnchor()-playInsets().top)/scale}

function survivalCamera(){if(!survival)return;camX=clamp(p.x-sw/scale/2,0,Math.max(0,W-sw/scale));camY=Math.max(-playInsets().top/scale,survival.routeY-survivalAnchor()/scale);updateTransforms()}

function sourceGroups(){return [...page.querySelectorAll('h1,h2,h3')].map((head,i)=>({title:head.textContent,heading:glyphs.filter(a=>head.contains(a.el)),sourceTop:localRect(head).y,hp:Math.round((head.tagName==='H1'?160:head.tagName==='H2'?55+i*3:32)*PAGE_ASSAULT.eliteScale)+[0,0,220,520,950,1050][level]})).filter(g=>g.heading.length)}

function resetSurvival(){if(level<1)return;document.body.classList.add('survival-one');$('#joy small').textContent='移动 / 躲避';$('#settings-sheet p').innerHTML='第 '+level+' 关 · '+PAGE_ASSAULT.name+'：'+PAGE_ASSAULT.description+'。<br>从页底向上推进，原网页就是战场。<br>WASD、方向键或摇杆移动；三把武器自动攻击。<br>正文、链接、导航和按钮文字都会从原位置袭来；收集蓝色墨点升级。';$('#fx').setAttribute('aria-label','网页推进战：移动躲避，文字从原网页位置出击');$('#view').setAttribute('aria-label','网页推进战场');const groups=sourceGroups(),titleIds=new Set(groups.flatMap(g=>g.heading.map(a=>a.id))),pending=glyphs.filter(a=>!titleIds.has(a.id)).sort((a,b)=>b.y-a.y||a.x-b.x);survival={phase:'ready',stage:0,pageCleared:false,bossStarted:false,groups,pending,titlePending:groups.slice().sort((a,b)=>b.sourceTop-a.sourceTop),actors:[],shots:[],projectiles:[],orbs:[],ink:0,hp:PAGE_ASSAULT.shield,maxHp:PAGE_ASSAULT.shield,damageTaken:0,damageBy:{},attackCounts:{beam:0,caster:0,charged:0},eraserIntercepts:0,hurtUntil:-1,spawned:0,killed:0,total:pending.length,eliteKills:0,eliteTotal:groups.length,sourceTotal:glyphs.length,nextSpawn:0,lastGun:-10,lastGrenade:-10,lastEraser:-10,stageAt:0,serial:0,weaponCounts:{gun:0,grenade:0,eraser:0},stick:{x:0,y:0},hits:[],escapes:0,pageBottom:localRect($('#survival-arena')).y,routeY:localRect($('#survival-arena')).y+100,offsetY:0,exposedTop:Infinity,progress:0,lastRender:-1};const fractions=level===1?[.03,.1,.21,.38,.60,.84]:Array.from({length:growth.nodes.length},(_,i)=>.045+.835*Math.pow(i/(growth.nodes.length-1),1.55));const thresholds=fractions.map(f=>Math.max(18,Math.round(glyphs.length*f)));growth.nodes.forEach((n,i)=>n.threshold=thresholds[i]);$('#survival-overlay').hidden=true;$('#survival-guide').hidden=false;$('#survival-skip').hidden=true;Object.assign(p,{x:W/2,y:survival.routeY,vx:0,vy:0,angle:-Math.PI/2,onGround:false});survivalCamera();renderSurvivalUI()}

function startSurvival(){if(survival?.phase==='ready')startSurvivalIntro()}

function finishSurvivalIntro(){if(!survival||!['ready','intro'].includes(survival.phase))return;survival.phase='battle';survival.stageAt=time;survival.nextSpawn=time+.12;clearHeldInput();$('#survival-skip').hidden=true;renderSurvivalUI()}

function detachSurvivalGlyph(a){a.alive=false;a.el.classList.add('gone')}
function spawnSurvivalGlyph(a,index){const strong=a.text==='出'||index%(level>=3?8:12)===(level>=3?7:11);detachSurvivalGlyph(a);const e={id:'letter-'+a.id,kind:'letter',source:a,text:a.text,display:a.text,x:a.x,y:a.y,w:a.w,h:a.h,fs:a.fs,font:a.font,color:a.color,hp:strong?PAGE_ASSAULT.strongHp:PAGE_ASSAULT.hp,maxHp:strong?PAGE_ASSAULT.strongHp:PAGE_ASSAULT.hp,alive:true,state:'warning',born:time,warmUntil:time+PAGE_ASSAULT.warmup,homeX:a.x,homeY:a.y,origin:{x:a.x,y:a.y},speed:PAGE_ASSAULT.letterSpeed+(index%4)*16,mode:index%(level===1?6:Math.max(2,7-level))===1?'chase':index%3===1?'cross':'dive'};if(PAGE_ASSAULT.casterEvery&&index%PAGE_ASSAULT.casterEvery===PAGE_ASSAULT.casterEvery-1){e.mode='caster';e.nextShot=time+1.1}survival.actors.push(e);survival.spawned++;return e}

function spawnSurvivalElite(group){const g=group||survival.groups[0];if(survival.actors.some(e=>e.id==='title-'+g.heading[0].id))return;for(const a of g.heading)detachSurvivalGlyph(a);const first=g.heading[0],last=g.heading.at(-1),e={id:'title-'+first.id,kind:'elite',source:g.heading,text:g.title,display:g.title,x:first.x,y:first.y,w:last.x+last.w-first.x,h:first.h,fs:first.fs,font:first.font,color:first.color,hp:g.hp,maxHp:g.hp,alive:true,state:'warning',born:time,warmUntil:time+.65,homeX:first.x,homeY:first.y,origin:{x:first.x,y:first.y},warning:null,nextShot:time+1.3};survival.actors.push(e);return e}

function survivalActive(){return survival?.actors.filter(e=>e.alive&&e.state==='active')||[]}
function survivalAttackables(){return survival?.actors.filter(e=>e.alive&&(e.state==='active'||level>=2&&e.state==='warning'))||[]}
function survivalRect(e){if(e.kind==='boss')return e;const cut=e.text==='出'&&e.hp===1?0:Math.floor(e.h*(1-e.hp/e.maxHp)*.55);return {x:e.x,y:e.y+cut,w:e.w,h:e.h-cut}}
function survivalHurtActor(e,damage,x,y){if(!e.alive||!(e.state==='active'||level>=2&&e.state==='warning'))return;if(e.kind==='boss'){survivalDamageBoss(e,damage,x,y);return}e.hp=Math.max(0,e.hp-damage);survival.hits.push({id:e.id,x,y,rect:survivalRect(e),at:time});if(survival.hits.length>30)survival.hits.shift();if(e.text==='出'&&e.hp===1)e.display='山';if(e.hp)return;e.alive=false;survival.killed+=e.kind==='letter'?1:0;survival.eliteKills+=e.kind==='elite'?1:0;const sources=Array.isArray(e.source)?e.source:[e.source];for(const a of sources){const old={x:a.x,y:a.y};a.alive=true;a.x=e.x;a.y=e.y;destroy(a,x,y,1);Object.assign(a,old)}survival.orbs.push({x:e.x+e.w/2,y:e.y+e.h/2,value:e.kind==='elite'?sources.length+6:1});if(e.kind==='elite'){if(survival.eliteKills%PAGE_ASSAULT.healEvery===0)survival.hp=Math.min(survival.maxHp,survival.hp+1);sound('heavy');rings.push({x:e.x+e.w/2,y:e.y,r:110,t:0,life:.45,heavy:true})}}
function survivalHurtPlayer(x,y,cause='letter'){if(survival.phase!=='battle'||time<survival.hurtUntil)return;survival.hp--;survival.damageTaken++;survival.damageBy[cause]=(survival.damageBy[cause]||0)+1;survival.hurtUntil=time+PAGE_ASSAULT.invincible;hitFeedback(x,y,true);if(survival.hp<=0){survival.phase='dead';clearHeldInput();paused=true;$('#paused').style.display='none';$('#survival-overlay').hidden=false;$('#survival-over-copy').textContent='已击败 '+survival.killed+' / '+survival.total+' 个字、'+survival.eliteKills+' / '+survival.eliteTotal+' 个标题。移动躲开文字，也可以靠近墨点选择升级。';$('#survival-retry').focus({preventScroll:true});renderMusic()}}
function survivalMove(dt){if(!['battle','clear'].includes(survival.phase))return;const s=survival;let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')||keys.has(' ')?1:0);if(s.stick.x||s.stick.y){dx=s.stick.x;dy=s.stick.y}const len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len}const speed=Math.min(320,230/scale),oldY=p.y,b=survivalBounds();if(s.phase==='battle'){const waiting=s.pending.filter(a=>a.y>=s.exposedTop).length,pressure=s.actors.filter(e=>e.alive).length;const advance=pressure>=55||waiting>100?5:pressure>=40||waiting>60?14:PAGE_ASSAULT.advance;if(!s.pageCleared)s.routeY=Math.max(survivalMinRoute(),s.routeY-advance*dt)}s.offsetY=clamp(s.offsetY+dy*speed*dt,-b.height*.42,b.height*.14);p.x=clamp(p.x+dx*speed*dt,18,W-18);p.y=s.routeY+s.offsetY;survivalCamera();const next=survivalBounds();p.y=clamp(p.y,next.top+45,next.bottom);s.offsetY=p.y-s.routeY;p.vx=dx*speed;p.vy=(p.y-oldY)/dt;p.onGround=false;p.step+=len*dt*12;p.recoil=Math.max(0,p.recoil-dt*30);s.progress=clamp((s.pageBottom+100-s.routeY)/Math.max(1,s.pageBottom+100-survivalMinRoute()),0,1)}

function survivalAim(){const range=GAME_CONFIG.gun.range,ox=p.x,oy=p.y-24,candidates=survivalAttackables().filter(e=>Math.hypot(e.x+e.w/2-ox,e.y+e.h/2-oy)<range);candidates.sort((a,b)=>Math.hypot(a.x+a.w/2-ox,a.y+a.h/2-oy)-Math.hypot(b.x+b.w/2-ox,b.y+b.h/2-oy));const e=candidates[0];if(e){const lead=Math.min(.9,Math.hypot(e.x+e.w/2-ox,e.y+e.h/2-oy)/760);p.angle=Math.atan2(e.y+e.h/2+(e.vyActual||0)*lead-oy,e.x+e.w/2+(e.vxActual||0)*lead-ox);p.face=Math.cos(p.angle)>=0?1:-1}else p.angle=-Math.PI/2;return e}
function survivalShot(kind,angle,stats){const dist=kind==='gun'?Math.min(36,Math.hypot((survivalAim()?.x||p.x)-p.x,(survivalAim()?.y||p.y)-p.y)*.3):18,spd=kind==='gun'?760:420;survival.weaponCounts[kind]++;survival.shots.push({id:++survival.serial,kind,x:p.x+Math.cos(angle)*dist,y:p.y-24+Math.sin(angle)*dist,vx:Math.cos(angle)*spd,vy:Math.sin(angle)*spd,life:kind==='gun'?1.5:1.65,remaining:GAME_CONFIG.gun.range,hits:new Set(),maxHits:kind==='gun'?stats.pierce:1,damage:kind==='gun'?stats.damage:stats.grenadeDamage,radius:stats.radius});p.recoil=kind==='gun'?2.5:4;flash=.08}
function survivalBlast(x,y,damage,radius){for(const e of survivalAttackables()){const r=survivalRect(e),dx=Math.max(r.x-x,0,x-r.x-r.w),dy=Math.max(r.y-y,0,y-r.y-r.h);if((e.kind==='boss'?actorBlastDistance(x,y,e):Math.hypot(dx,dy))<=radius)survivalHurtActor(e,damage*(e.kind==='boss'?3:1),x,y)}hitFeedback(x,y,true);rings.push({x,y,r:radius,t:0,life:.36,heavy:true})}
function survivalWeapons(){const s=survival,st=survivalStats(),e=survivalAim();if(e&&time-s.lastGun>=1/st.rate){s.lastGun=time;const angle=p.angle;survivalShot('gun',angle,st);for(let i=0;i<st.fan;i++)survivalShot('gun',angle+(i-(st.fan-1)/2)*.13+(i%2?.1:-.1),st);sound('fire')}if(e&&time-s.lastGrenade>=st.cooldown){s.lastGrenade=time;const lead=Math.min(1.3,Math.hypot(e.x-p.x,e.y-p.y)/420),angle=Math.atan2(e.y+e.h/2+(e.vyActual||0)*lead-(p.y-24),e.x+e.w/2+(e.vxActual||0)*lead-p.x);survivalShot('grenade',angle,st)}if(time-s.lastEraser>=st.eraserCooldown){s.lastEraser=time;s.weaponCounts.eraser++;const x=p.x,y=p.y-20;for(const a of survivalAttackables()){const r=survivalRect(a),cx=clamp(x,r.x,r.x+r.w),cy=clamp(y,r.y,r.y+r.h);if((a.kind==='boss'?actorBlastDistance(x,y,a):Math.hypot(cx-x,cy-y))<=st.eraserRange)survivalHurtActor(a,a.kind==='boss'?st.eraserDamage*.4:st.eraserDamage,cx,cy)}s.projectiles=s.projectiles.filter(b=>{if(Math.hypot(b.x-x,b.y-y)>st.eraserRange)return true;b.guardHp=(b.guardHp||1)-(st.guardDamage||1);b.hitUntil=time+.08;if(b.guardHp<=0){s.eraserIntercepts++;return false}return true});rings.push({x,y,r:st.eraserRange,t:0,life:.2,heavy:false})}}
function survivalProjectiles(dt){const s=survival,b=survivalBounds();for(let i=s.shots.length-1;i>=0;i--){const q=s.shots[i],step=Math.min(q.life,dt),travel=Math.min(q.remaining,Math.hypot(q.vx,q.vy)*step),ratio=travel/Math.hypot(q.vx,q.vy),nx=q.x+q.vx*ratio,ny=q.y+q.vy*ratio;let stop=false;const hits=survivalAttackables().map(e=>({e,t:e.kind==='boss'?actorSegment(q.x,q.y,nx,ny,e,1):segmentBox(q.x,q.y,nx,ny,survivalRect(e),1)})).filter(h=>h.t!==null).sort((a,b)=>a.t-b.t);for(const {e,t} of hits){if(!e.alive||q.hits.has(e.id))continue;const x=q.x+(nx-q.x)*t,y=q.y+(ny-q.y)*t;q.hits.add(e.id);q.x=x;q.y=y;if(q.kind==='grenade'){survivalBlast(x,y,q.damage,q.radius);stop=true}else{survivalHurtActor(e,q.damage,x,y);hitFeedback(x,y);stop=e.alive||q.hits.size>=q.maxHits}if(stop)break}if(!stop){q.x=nx;q.y=ny}q.life-=step;q.remaining-=travel;if(!stop&&(q.life<=0||q.remaining<=0||q.x<b.left-100||q.x>b.right+100||q.y<b.top-100||q.y>b.bottom+100)){if(q.kind==='grenade')survivalBlast(q.x,q.y,q.damage,q.radius);stop=true}if(stop)s.shots.splice(i,1);if(paused)break}
 const player={x:p.x-8,y:p.y-40,w:16,h:40};for(let i=s.projectiles.length-1;i>=0;i--){const q=s.projectiles[i],nx=q.x+q.vx*dt,ny=q.y+q.vy*dt;if(segmentBox(q.x,q.y,nx,ny,player,3)!==null){survivalHurtPlayer(nx,ny,'projectile');s.projectiles.splice(i,1);continue}q.x=nx;q.y=ny;q.life-=dt;q.age=(q.age||0)+dt;if(q.life<=0||q.x<b.left-50||q.x>b.right+50||q.y>b.bottom+50)s.projectiles.splice(i,1)}}
function survivalActors(dt){const s=survival,b=survivalBounds(),player={x:p.x-7,y:p.y-39,w:14,h:38};for(const e of s.actors){if(!e.alive)continue;if(e.kind==='boss'){survivalUpdateBoss(dt);continue}if(e.state==='returning'){if(time<e.returnAt)continue;e.x=clamp(e.x,b.left+10,b.right-e.w-10);e.y=b.top-10;e.state='warning';e.warmUntil=time+.3;e.mode='chase'}if(e.state==='warning'){if(time<e.warmUntil)continue;e.state='active';e.born=time;const dx=p.x-e.x-e.w/2,dy=p.y-22-e.y-e.h/2,d=Math.max(1,Math.hypot(dx,dy));e.vx=dx/d*e.speed;e.vy=dy/d*e.speed}const previous={x:e.x,y:e.y},age=time-e.born;if(e.kind==='elite'){const targetX=clamp(p.x-e.w/2+Math.sin(age*.9)*110,12,W-e.w-12),targetY=b.top+24+Math.sin(age)*16;e.x+=clamp(targetX-e.x,-110*dt,110*dt);e.y+=clamp(targetY-e.y,-95*dt,95*dt);survivalEliteAttack(e,b)}else{if(e.mode==='caster'){survivalCasterAttack(e,b,dt)}else{if(e.mode==='chase'){const dx=p.x-e.x-e.w/2,dy=p.y-22-e.y-e.h/2,d=Math.max(1,Math.hypot(dx,dy)),turn=Math.min(1,dt*PAGE_ASSAULT.turn);e.vx+=(dx/d*e.speed-e.vx)*turn;e.vy+=(dy/d*e.speed-e.vy)*turn}e.x+=(e.vx+(e.mode==='cross'?Math.sin(age*3)*40:0))*dt;e.y+=e.vy*dt}const r=survivalRect(e);if(r.x<player.x+player.w&&r.x+r.w>player.x&&r.y<player.y+player.h&&r.y+r.h>player.y)survivalHurtPlayer(e.x,e.y);if(age>3&&(e.y>b.bottom+75||e.y<b.top-150||e.x<b.left-400||e.x>b.right+400)){e.state='returning';e.returnAt=time+2.5;s.escapes++}}e.vxActual=(e.x-previous.x)/dt;e.vyActual=(e.y-previous.y)/dt}}

function survivalInk(dt){const s=survival,b=survivalBounds();for(let i=s.orbs.length-1;i>=0;i--){const o=s.orbs[i],dx=p.x-o.x,dy=p.y-20-o.y,d=Math.hypot(dx,dy);if(d<23){s.ink+=o.value;s.orbs.splice(i,1);growthDirty=true;continue}if(d<155+getWeaponStats().arsenal*3||o.y>b.bottom-10||o.y<b.top-40){const v=Math.min(d,380*dt);o.x+=dx/d*v;o.y+=dy/d*v}else o.y=Math.min(b.bottom-15,o.y+70*dt)}}

function survivalStage(){const s=survival;if(s.phase!=='battle')return;const b=survivalBounds();s.exposedTop=Math.min(s.exposedTop,b.top-12);let capacity=PAGE_ASSAULT.maxActive-s.actors.filter(e=>e.alive).length;if(capacity>0&&time>=s.nextSpawn){let batch=0;while(capacity>0&&batch<PAGE_ASSAULT.batch&&s.pending.length&&s.pending[0].y>=s.exposedTop){const a=s.pending.shift();spawnSurvivalGlyph(a,s.spawned);batch++;capacity--}if(batch)s.nextSpawn=time+PAGE_ASSAULT.spawnInterval}if(s.titlePending.length&&s.titlePending[0].sourceTop>=s.exposedTop&&s.actors.filter(e=>e.alive&&e.kind==='elite').length<PAGE_ASSAULT.elites){spawnSurvivalElite(s.titlePending.shift())}if(s.progress>=1&&!s.pending.length&&!s.titlePending.length&&!s.actors.some(e=>e.alive)){s.pageCleared=true;if(level===5&&!s.bossStarted){survivalStartBoss();return}if(level===5&&!boss.defeated)return;s.phase='clear';growthDirty=true;progress()}}

function survivalFrame(dt){const s=survival;if(!paused){time+=dt;if(started&&!ending&&!settled){if(s.phase==='intro')survivalIntroStep(dt);else if(['battle','clear'].includes(s.phase)){activeTime+=dt;survivalMove(dt);if(s.phase==='battle'){survivalStage();survivalActors(dt);if(!paused)survivalWeapons();if(!paused)survivalProjectiles(dt)}if(!paused)survivalInk(dt);if(!paused)progress()}}if(!paused)updateEffects(dt);updateTransforms()}renderSurvivalUI()}

function drawSurvivalWorld(){const s=survival;if(!s||!['battle','interlude','clear','dead'].includes(s.phase))return;const b=survivalBounds();ctx.save();
 for(const e of s.actors.filter(e=>e.alive)){if(e.kind==='boss')continue;const r=survivalRect(e);ctx.save();ctx.beginPath();ctx.rect(r.x-1,r.y,r.w+2,r.h+1);ctx.clip();ctx.font=e.font||e.fs+'px sans-serif';ctx.fillStyle=e.color||'#283d52';ctx.textBaseline='top';ctx.textAlign='left';ctx.fillText(e.display,e.x,e.y-1);ctx.restore();if(e.state==='warning'){ctx.strokeStyle='#c6964770';ctx.lineWidth=1;ctx.strokeRect(e.x-2,e.y-2,e.w+4,e.h+4)}if(e.kind==='elite'){ctx.fillStyle='#e1e7ec';ctx.fillRect(e.x,e.y-12,e.w,4);ctx.fillStyle='#6483a3';ctx.fillRect(e.x,e.y-12,e.w*e.hp/e.maxHp,4);ctx.font='10px Arial';ctx.fillStyle='#8b7558';ctx.textAlign='center';ctx.fillText('标题精英',e.x+e.w/2,e.y-19);if(e.warning)drawSurvivalLanes(e,b)}if(e.kind==='letter'&&e.mode==='caster'){ctx.strokeStyle='#b9634e';ctx.lineWidth=1;ctx.beginPath();ctx.arc(e.x+e.w/2,e.y+e.h/2,Math.max(e.w,e.h)/2+4,0,Math.PI*2);ctx.stroke();if(e.warning){ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(e.x+e.w/2,e.y+e.h);ctx.lineTo(e.warning.targetX,e.warning.targetY);ctx.stroke();ctx.setLineDash([])}}if(e.beam&&time<e.beam.until){for(const x of e.beam.lanes){ctx.fillStyle='#c5844560';ctx.fillRect(x-28,e.y+e.h,56,b.bottom-e.y-e.h)}}if(hitDebug){ctx.strokeStyle='#df49a1';ctx.strokeRect(r.x,r.y,r.w,r.h)}}
 for(const q of s.shots){ctx.strokeStyle=q.kind==='grenade'?'#c98c32':'#3895ba';ctx.lineWidth=q.kind==='grenade'?3:2;ctx.beginPath();ctx.moveTo(q.x-q.vx*.018,q.y-q.vy*.018);ctx.lineTo(q.x,q.y);ctx.stroke();if(q.kind==='grenade'){ctx.fillStyle='#cc974d';ctx.fillRect(q.x-3,q.y-3,6,6)}}for(const q of s.projectiles){if(q.source==='boss'){drawBossProjectile(q);if(q.guardMax>1)drawSurvivalArmor(q);continue}drawSurvivalHostile(q)}for(const o of s.orbs){ctx.beginPath();ctx.fillStyle='#387ca3';ctx.arc(o.x,o.y,o.value>1?6:3.4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#88b6c8';ctx.lineWidth=1;ctx.stroke()}if(time<s.hurtUntil){ctx.strokeStyle='#cc9864';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y-22,26,0,Math.PI*2);ctx.stroke()}if(hitDebug){for(const h of s.hits.filter(h=>time-h.at<.6)){ctx.fillStyle='#ef4098';ctx.fillRect(h.x-2,h.y-2,4,4)}}ctx.restore()}
function renderSurvivalUI(){const s=survival;if(!s||s.phase==='free')return;$('#quick-next').hidden=!growth.complete||level===5||ending||settled;$('#find-enemy').hidden=true;s.lastRender=time;s.renderPhase=s.phase;s.renderHp=s.hp;const st=survivalStats(),next=growth.nodes.find(n=>n.state==='locked');$('#current-stage').textContent='LEVEL 0'+level+' · '+PAGE_ASSAULT.name+' · '+(['','招聘网页','沟通记录',STAGES[3].name,STAGES[4].name,STAGES[5].name][level]);$('#start-run').textContent='开始推进';$('#battle-rule').textContent='通关：清空全页文字与标题'+(level===5?'，击败最终 Boss':'');$('#battle-summary').textContent=s.phase==='clear'?'✓ 已通关':s.pageCleared&&level===5?'最终 Boss '+Math.ceil(boss.hp)+' / '+boss.maxHp:'向上推进 '+Math.round(s.progress*100)+'% · 标题 '+s.eliteKills+'/'+s.eliteTotal;$('#battle-remaining').textContent='文字 '+s.killed+'/'+s.total+' · 墨点 '+s.ink;$('#battle-meter').max=s.total+s.eliteTotal;$('#battle-meter').value=s.killed+s.eliteKills;if(level===5&&s.pageCleared&&boss.active){$('#battle-meter').max=boss.maxHp;$('#battle-meter').value=boss.maxHp-boss.hp;$('#battle-meter').setAttribute('aria-label','最终 Boss 战进度')}else $('#battle-meter').setAttribute('aria-label','本关网页清空进度');$('#quick-shield').textContent='生命 '+'●'.repeat(Math.max(0,s.hp))+'○'.repeat(Math.max(0,s.maxHp-s.hp));$('#next-upgrade').textContent=next?'升级还差 '+Math.max(0,next.threshold-s.ink)+' 墨点':growth.nodes.length+' 次改造已解锁';$('#mission-rule').textContent='从页底向上推进，清空整页文字与标题'+(level===5?'并击败最终 Boss':'')+'后通关。';$('#goals').hidden=true;$('#enemy-progress').hidden=false;$('#enemy-progress').textContent=PAGE_ASSAULT.name+'：'+PAGE_ASSAULT.description+'。\n正文、链接、导航、按钮和侧栏文字全部参与。\n每个字只出击一次；未击败的字会追赶，不增加额外配额。';$('#growth-status').textContent='墨点 '+s.ink+(next?' / '+next.threshold:'')+' · 改造 '+growth.nodes.filter(n=>n.state==='claimed').length+'/'+growth.nodes.length;$('#growth-meter').max=next?.threshold||growth.nodes.at(-1).threshold;$('#growth-meter').value=s.ink;$('#compact-task').textContent='文字 '+s.killed+'/'+s.total+' · 标题 '+s.eliteKills+'/'+s.eliteTotal+(level===5?' · Boss '+(boss.defeated?'✓':boss.active?Math.ceil(boss.hp):'待出场'):'');$('#mission-completion').textContent=$('#compact-task').textContent;$('#survival-guide').hidden=s.phase!=='ready';$('#survival-copy').textContent='难度：'+PAGE_ASSAULT.name+' · '+PAGE_ASSAULT.description;$('#survival-guide').style.top=($('#battle-strip').getBoundingClientRect().bottom+8)+'px';$('#clear-continue').textContent='回到原页自由拆';for(const button of document.querySelectorAll('#weapon-dock button')){const w=+button.dataset.weapon;button.setAttribute('aria-pressed',String(w===weapon));button.querySelector('span').textContent=w===0?`每秒 ${st.rate.toFixed(1)} 发 · ${st.fan+1} 弹道`:w===1?`半径 ${st.radius} · 伤害 ${st.grenadeDamage}`:`近身半径 ${st.eraserRange} · 伤害 ${st.eraserDamage}`;button.querySelector('small').textContent=(w===weapon?'主武器 · ':'支援 · ')+(w===0?'自动连发':w===1?`${st.cooldown.toFixed(2)}s`:`${st.eraserCooldown.toFixed(2)}s`+(level>=3?` · 削甲 ${st.guardDamage}`:''))}}

// Preserve legacy dismantling only after clearing; every level uses this battle loop.
const survivalOldBegin=begin;begin=function(){survivalOldBegin();if(level>=1&&survival)startSurvival()};
const survivalOldFire=fire;fire=function(h){if(level>=1&&survival&&survival.phase!=='free')return;return survivalOldFire(h)};
const survivalOldPlayer=drawPlayer;drawPlayer=function(){if(level>=1&&survival&&survival.phase==='intro')return;survivalOldPlayer()};
const survivalOldRender=renderBattleUI;renderBattleUI=function(){survivalOldRender();if(level>=1)renderSurvivalUI()};
const survivalOldReset=resetGame;resetGame=function(){survivalOldReset();if(level>=1)resetSurvival()};
const survivalOldResize=resize;resize=function(){survivalOldResize();if(level>=1&&survival&&survival.phase!=='free'){if(survival.phase==='intro'){survivalIntroCamera();renderSurvivalUI();return}survival.routeY=Math.max(survivalMinRoute(),survival.routeY);survivalCamera();const b=survivalBounds();p.y=clamp(survival.routeY+survival.offsetY,b.top+45,b.bottom);survival.offsetY=p.y-survival.routeY;survival.lastRender=-1;renderSurvivalUI()}};
const survivalOldJoy=updateJoy;updateJoy=function(e){if(level<1||!survival||survival.phase==='free')return survivalOldJoy(e);const r=$('#joy').getBoundingClientRect();let dx=(e.clientX-r.left-r.width/2)/(r.width*.38),dy=(e.clientY-r.top-r.height/2)/(r.height*.38),len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len}survival.stick={x:Math.abs(dx)<.12?0:dx,y:Math.abs(dy)<.12?0:dy};$('#joy-thumb').style.transform=`translate(calc(-50% + ${dx*26}px),calc(-50% + ${dy*26}px))`};
const survivalOldClear=clearTouchControls;clearTouchControls=function(){survivalOldClear();if(survival)survival.stick={x:0,y:0}};
for(const event of ['pointerup','pointercancel','lostpointercapture'])$('#joy').addEventListener(event,()=>{if(survival&&joyPointer===null)survival.stick={x:0,y:0}});
const survivalOldContinue=continueAfterClear;continueAfterClear=function(){survivalOldContinue();if(level>=1&&survival){survival.phase='free';document.body.classList.remove('survival-one');$('#joy small').textContent='移动 / 飞升';$('#settings-sheet p').innerHTML=survivalSettingsCopy;$('#survival-guide').hidden=true;survivalOldRespawn(false);setupGameUI();renderBattleUI()}};$('#clear-continue').onclick=continueAfterClear;
const survivalOldRespawn=respawn;respawn=function(m){if(level>=1&&survival&&survival.phase!=='free'){if(survival.phase==='battle'){p.x=W/2;survival.offsetY=0;p.y=survival.routeY;survivalCamera()}return}survivalOldRespawn(m)};
const survivalOldDescription=modDescription;modDescription=function(k){if(level<1||!survival||survival.phase==='free')return survivalOldDescription(k);const before=survivalStats();mods[k]++;const after=survivalStats();mods[k]--;return (k==='A'?`连发 ${before.rate.toFixed(1)} → ${after.rate.toFixed(1)} 发/秒；贯穿 ${before.pierce} → ${after.pierce}；伤害 ${before.damage} → ${after.damage}`:k==='B'?`弹道 ${before.fan+1} → ${after.fan+1}；连发 ${before.rate.toFixed(1)} → ${after.rate.toFixed(1)} 发/秒`:k==='C'?`榴弹半径 ${before.radius} → ${after.radius}`+(level>=3?`；重弹削甲 ${before.guardDamage} → ${after.guardDamage}（爆破 VIII 提升）`:''):`榴弹冷却 ${before.cooldown} → ${after.cooldown} 秒`)+`；近身橡皮擦 ${before.eraserRange} → ${after.eraserRange}；爆破伤害 ${before.grenadeDamage} → ${after.grenadeDamage}`};
$('#survival-skip').onclick=finishSurvivalIntro;
$('#survival-retry').onclick=()=>{resetGame();begin()};
$('#survival-review').onclick=()=>{resetGame()};
