musicEnabled=false;muted=true;const rows=[];function check(name,pass,data){rows.push({name,pass:!!pass,data})}function fresh(){time=0;closeGameSheets();resetGame();begin();muted=true;invincibleUntil=1e6}function drain(){while(pendingNodes().length){if(!choiceNode)openUpgrade();claimUpgrade(openChoices[0])}}function ticks(n){for(let i=0;i<n;i++){if(!paused){time+=1/60;move(1/60);updateBullets(1/60);updateCombat(1/60);updateEffects(1/60)}drain()}}
fresh();check('Air support available before destruction in every stage',airMobilityAvailable()&&goneGlyphs===0);Object.assign(p,{x:400,y:H-25,vy:0});keys.add('w');ticks(90);check('Can ascend from bottom with intact page',p.y<H-300,{y:p.y,H});keys.clear();ticks(40);const held=p.y;ticks(20);check('Releasing ascent hovers',Math.abs(p.y-held)<2);for(const a of all)destroy(a,a.x,a.y);progress();drain();Object.assign(p,{y:H-25,vy:0});keys.add('w');ticks(90);check('Can ascend after all terrain is gone',p.y<H-300);keys.clear();
fresh();const basic=blankMods();mods={...basic};const st0=getWeaponStats();mods.A=1;const st1=getWeaponStats();check('Gun upgrade improves grenade radius and damage',st1.radius>st0.radius&&st1.grenadeDamage>st0.grenadeDamage,{before:st0,after:st1});check('Gun upgrade improves grenade cooldown',st1.cooldown<st0.cooldown);check('Gun upgrade improves eraser range damage and cooldown',st1.eraserRange>st0.eraserRange&&st1.eraserDamage>st0.eraserDamage&&st1.eraserCooldown<st0.eraserCooldown);mods={...basic,B:3};check('Gun split branch also upgrades other weapons',getWeaponStats().effectiveC===3&&getWeaponStats().eraserLevel===3);mods={A:1,B:2,C:0,D:0};const combined=getWeaponStats();mods.A++;check('Both gun branches contribute to shared equipment tier',getWeaponStats().radius>combined.radius&&getWeaponStats().eraserRange>combined.eraserRange);mods={A:12,B:12,C:12,D:12};let st=getWeaponStats();check('Maximum inherited build has finite weapon stats',Object.values(st).filter(v=>typeof v==='number').every(Number.isFinite)&&st.radius===250&&st.cooldown===.52);mods={...basic};
// Actual UI pointer event routing, with capture mocked ONLY in this deterministic fixture.
for(const el of [$('#joy'),$('#fire-pad')])el.setPointerCapture=()=>{};
function touch(el,type,id,dx=0,dy=0){const r=el.getBoundingClientRect();el.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerType:'touch',pointerId:id,clientX:r.x+r.width/2+dx,clientY:r.y+r.height/2+dy,button:0}))}
touch($('#joy'),'pointerdown',41,30,-35);touch($('#fire-pad'),'pointerdown',42);check('Two fingers hold movement and firing independently',joyPointer===41&&firePointer===42&&mobileKeys.has('right')&&mobileKeys.has('jump')&&touchFire);touch($('#joy'),'pointerup',41);check('Releasing joystick preserves firing',joyPointer===null&&firePointer===42&&touchFire&&!mobileKeys.size);touch($('#joy'),'pointerdown',43,-30,0);touch($('#fire-pad'),'pointerup',42);check('Releasing fire preserves joystick',firePointer===null&&!touchFire&&joyPointer===43&&mobileKeys.has('left'));touch($('#joy'),'pointercancel',43);check('Cancelled joystick clears motion',!mobileKeys.size&&joyPointer===null);touch($('#fire-pad'),'pointerdown',44);window.dispatchEvent(new Event('blur'));check('Blur clears all held input',firePointer===null&&!touchFire&&!mobileKeys.size);touch($('#fire-pad'),'pointerdown',45);selectWeapon(1);check('Weapon switch never sticks fire',firePointer===null&&!touchFire);touch($('#joy'),'pointerdown',46,30,0);openGameSheet('#settings-sheet');check('Settings pause and clear touch input',paused&&joyPointer===null&&!$('#settings-sheet').hidden);closeGameSheets();check('Closing settings resumes correctly',!paused&&$('#settings-sheet').hidden);openGameSheet('#growth-hud');check('Mission opens visible sheet',$('#growth-hud').classList.contains('sheet-open')&&paused);closeGameSheets();
check('All new controls excluded from terrain',all.every(a=>!a.el||page.contains(a.el))&&[$('#joy'),$('#fire-pad'),$('#weapon-dock button'),$('#settings-toggle')].every(uiTarget));
if(level===1){openGameSheet('#growth-hud');$('#goals button').click();check('Level one target travel works through paused mission',!!guidedTarget&&!paused&&!$('#growth-hud').classList.contains('sheet-open'));for(const t of targets)for(const a of t.items)destroy(a,a.x,a.y);progress();drain();check('Level one retains three-target win',growth.complete);}
else {
 fresh();ticks(210);check('Enemies spawn without destroying page',waves.spawned>0&&goneGlyphs===0&&waveAlive().length>0,{waves});check('Boss waits until finite small monsters finished',level!==5||!boss.active);const n=waves.killed,e=waveAlive()[0];hurtEnemy(e,1e6,p.x);hurtEnemy(e,1e6,p.x);check('Enemy death counts once',waves.killed===n+1);for(const t of targets)for(const a of t.items)destroy(a,a.x,a.y);progress();drain();check('Destroying old sources does not kill monsters or win',waveAlive().length>0&&!growth.complete&&targets.every(t=>!t.done));
 fresh();let safety=0,seen=new Set();while(!waves.ended&&safety++<3000){ticks(1);for(const e of waveAlive()){seen.add(e.id);hurtEnemy(e,1e6,p.x)}progress();drain()}
 check('Every finite wave must spawn and die',waves.ended&&waves.spawned===waves.total&&waves.killed===waves.total&&seen.size===waves.total,{safety,waves});check('Kills alone preserve webpage yet advance win',goneGlyphs===0&&targets.every(t=>!t.done)&&(level===5?!growth.complete:growth.complete));if(level===5){check('Final Boss appears near player after last wave',boss.active&&boss.alive&&Math.abs(boss.y-p.y)<boss.h);hurtBoss(1e6,p.x);progress();check('Boss death completes final level',growth.complete&&boss.defeated)}
 const killed=waves.killed;ticks(300);check('Completed waves never respawn',waves.killed===killed&&waves.spawned===waves.total&&!waveAlive().length);$('#continue-break').click();const a=glyphs.find(a=>a.alive&&a.y>100);const before=goneGlyphs;impact(a.x,a.y);progress();drain();check('Continue dismantling works after combat clear',growth.complete&&goneGlyphs>before&&!settled&&!ending);requestEnd();check('End commits result once',ending&&growth.committed&&!!run.results[level]);const result=JSON.stringify(run.results[level]);requestEnd();check('Repeated settlement does not duplicate',JSON.stringify(run.results[level])===result);fresh();check('Retry resets waves and restores terrain',waves.killed===0&&waves.spawned===0&&all.every(a=>a.alive)&&airMobilityAvailable());
 // Use actual weapon paths on isolated enemies. Terrain is removed only to make obstruction explicit.
 for(let w=0;w<3;w++){fresh();for(const a of all)destroy(a,a.x,a.y);progress();drain();enemies=[];waves.nextAt=1e6;mods={A:3,B:0,C:3,D:3};const e=spawnEnemy(waveSource,'chaser',{x:550,y:550,w:82,h:52});e.waveMember=true;const before=e.hp;Object.assign(p,{x:465,y:600,angle:0,face:1});pointer.moved=false;selectWeapon(w);p.angle=Math.atan2(576-(p.y-24),591-p.x);time+=10;fire();for(let i=0;i<60;i++)updateBullets(1/60);check('Weapon '+(w+1)+' uses real collision against monster',!e.alive||e.hp<before,{hp:e.hp,before});}
}
const out=document.createElement('pre');out.id='results';out.style='position:fixed;inset:0;z-index:99;background:white;overflow:auto';out.textContent=JSON.stringify({passed:rows.every(r=>r.pass),count:rows.length,failed:rows.filter(r=>!r.pass),rows},null,2);document.body.append(out);paused=true;
