let viewZoom=1,joyPointer=null,firePointer=null,stageFirePointer=null,fireAim=null,uiStamp='',sheetPaused=false;
function mobileLayout(){return isTouch||innerWidth<=760||(innerWidth<=1000&&innerHeight<500)}
function playInsets(){const mobile=mobileLayout(),strip=$('#battle-strip').getBoundingClientRect();let bottom=mobile?(innerHeight<500?110:200):105;const controls=[...document.querySelectorAll(mobile?'#joy,#fire-pad,#weapon-dock':'#weapon-dock')].map(el=>el.getBoundingClientRect()).filter(r=>r.width&&r.height);if(controls.length)bottom=Math.max(bottom,innerHeight-Math.min(...controls.map(r=>r.top))+12);return {top:Math.max(112,strip.bottom+8),bottom}}

function openGameSheet(id){if(choiceNode||ending)return;closeGameSheets();sheetPaused=!paused&&!ending&&!settled&&!choiceNode;if(sheetPaused)togglePause();$('#paused').style.display='none';$(id).hidden=false;if(id==='#growth-hud')$(id).classList.add('sheet-open');$('#task-toggle').setAttribute('aria-expanded',String(id==='#growth-hud'));$('#settings-toggle').setAttribute('aria-expanded',String(id==='#settings-sheet'))}
function closeGameSheets(){const was=sheetPaused;sheetPaused=false;$('#settings-sheet').hidden=true;$('#growth-hud').classList.remove('sheet-open');$('#task-toggle').setAttribute('aria-expanded','false');$('#settings-toggle').setAttribute('aria-expanded','false');if(was&&paused&&!choiceNode&&!ending&&!settled)togglePause()}
function missionText(){return level===1?`拆除目标 ${targets.filter(t=>t.done).length} / 3`:waves?`第 ${Math.min(waves.index+1,GAME_CONFIG.waves[level].length)} / ${GAME_CONFIG.waves[level].length} 波 · 已击败 ${waves.killed} / ${waves.total}`+(level===5?' · Boss '+(boss?.defeated?'✓':boss?.active?Math.ceil(boss.hp)+' / '+boss.maxHp:'待登场'):''):''}
function renderBattleUI(){if(!growth)return;const st=getWeaponStats(),summary=missionText(),next=growth.nodes.find(n=>n.state==='locked');$('#current-stage').textContent='LEVEL 0'+level+' · '+(STAGES[level]?.name||(level===1?'招聘网页':'沟通记录'));$('#battle-summary').textContent=summary;$('#battle-meter').max=level===1?3:waves.total+(level===5?1:0);$('#battle-meter').value=level===1?targets.filter(t=>t.done).length:waves.killed+(level===5&&boss.defeated?1:0);$('#quick-shield').textContent=level===1?'自由拆解':'护盾 '+ '●'.repeat(shield)+'○'.repeat(Math.max(0,combatConfig.shield-shield));$('#next-upgrade').textContent=next?'升级还差 '+Math.max(0,next.threshold-goneGlyphs)+' 字':'本关升级已完成';$('#quick-finish').hidden=!growth.complete;$('#find-enemy').hidden=level===1||growth.complete;$('#find-enemy').textContent=level===5&&boss.active?'找 Boss':'找小怪';$('#start-run').hidden=started;$('#pause-game').textContent=paused?'继续':'暂停';
 $('#build').textContent=`枪械 ${roman[st.arsenal]||'基础'} · 榴弹 ${roman[st.effectiveC]||'基础'} · 橡皮擦 ${roman[st.eraserLevel]||'基础'}`;$('#compact-task').textContent=summary;$('#mission-completion').textContent=summary;$('#mission-rule').textContent=growth.complete?'通关！可以结算或继续拆网页':level===1?'拆掉三处目标，各 40% 即可通关':level===5?'清完 '+waves.total+' 只小怪，再击败最终 Boss':'清完 '+waves.total+' 只小怪即可通关';$('#goals').hidden=level>=2;
 $('#enemy-progress').hidden=level===1;$('#enemy-progress').textContent=waves?`场上 ${waveAlive().length} 只 · 待出现 ${waves.total-waves.spawned} 只\n怪物不会无限刷新。拆网页能升级装备，但不要求拆掉三处话语。`:'';
 if(level===5){$('#boss-hud').hidden=!boss.active;$('#boss-alert').style.top=($('#battle-strip').getBoundingClientRect().bottom+8)+'px';}
 const stamp=JSON.stringify({mods,weapon});if(uiStamp!==stamp){uiStamp=stamp;for(const b of document.querySelectorAll('#weapon-dock button')){const w=+b.dataset.weapon;b.setAttribute('aria-pressed',String(w===weapon));b.querySelector('span').textContent=w===0?`贯穿 ${st.pierce} · 副弹 ${st.split.count}`:w===1?`半径 ${st.radius} · 伤害 ${st.grenadeDamage}`:`距离 ${st.eraserRange} · 伤害 ${st.eraserDamage}`}}
 for(const b of document.querySelectorAll('#weapon-dock button')){const w=+b.dataset.weapon,remain=w===1?Math.max(0,st.cooldown-(time-lastHeavy)):w===2?Math.max(0,st.eraserCooldown-(time-lastErase)):0;b.querySelector('small').textContent=remain>.02?'冷却 '+remain.toFixed(1)+'s':w===0?'按住连续射击':'就绪';}
}
function setupGameUI(){document.body.classList.add('mobile-wave-ui');document.body.style.setProperty('--game-accent',['','#377bd8','#42a38b','#ba8043','#9764bd','#bb526a'][level]);$('#settings-level').append($('#level-picker'),$('#switch-note'));$('#mission-toggle').textContent='关闭';$('#mission-toggle').onclick=closeGameSheets;$('#task-toggle').onclick=()=>$('#growth-hud').classList.contains('sheet-open')?closeGameSheets():openGameSheet('#growth-hud');$('#settings-toggle').onclick=()=>$('#settings-sheet').hidden?openGameSheet('#settings-sheet'):closeGameSheets();$('#settings-close').onclick=closeGameSheets;$('#start-run').onclick=()=>{begin();renderBattleUI();focusGame()};$('#pause-game').onclick=()=>{closeGameSheets();togglePause();renderBattleUI()};$('#quick-finish').onclick=requestEnd;$('#find-enemy').onclick=guideNearestEnemy;$('#view-zoom').onchange=e=>{viewZoom=+e.target.value;resize();manualUntil=0};for(const b of document.querySelectorAll('#weapon-dock button'))b.onclick=()=>{selectWeapon(+b.dataset.weapon);renderBattleUI()};$('#boss-guide').onclick=guideNearestEnemy;
 $('#hint strong').textContent=level===1?'第一关 · 拆掉三处压力话语':'第 '+level+' 关 · 清空小怪'+(level===5?'，迎战 Boss':'');$('#hint-copy').innerHTML=(level===1?'任务按钮里可前往三处目标。':'共 '+waves.total+' 只小怪，有限波次，打完即可通关'+(level===5?'前迎战最终 Boss':'')+'。')+'<br>全关卡可以飞升：空格 / W 上升，S 下降，松开悬停。<br>手机：左摇杆移动，右侧按住射击；拖动瞄准。<br>升级枪械会同步提升榴弹与橡皮擦。';renderAirMobility();renderBattleUI();
}
function clearTouchControls(){joyPointer=null;firePointer=null;stageFirePointer=null;fireAim=null;touchFire=false;mobileKeys.clear();$('#joy-thumb').style.transform='translate(-50%,-50%)';$('#joy').classList.remove('held');$('#fire-pad').classList.remove('held')}
function updateJoy(e){const r=$('#joy').getBoundingClientRect(),dx=clamp((e.clientX-r.left-r.width/2)/(r.width*.4),-1,1),dy=clamp((e.clientY-r.top-r.height/2)/(r.height*.4),-1,1);for(const key of ['left','right','jump','drop'])mobileKeys.delete(key);if(dx<-.22)mobileKeys.add('left');if(dx>.22)mobileKeys.add('right');if(dy<-.22)mobileKeys.add('jump');if(dy>.22)mobileKeys.add('drop');$('#joy-thumb').style.transform=`translate(calc(-50% + ${dx*26}px),calc(-50% + ${dy*26}px))`;manualUntil=0}
function updateFireAim(e){const r=$('#fire-pad').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2;fireAim=Math.hypot(dx,dy)>14?{dx,dy}:null}
$('#joy').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(paused||ending||settled||joyPointer!==null)return;begin();joyPointer=e.pointerId;$('#joy').setPointerCapture(e.pointerId);$('#joy').classList.add('held');updateJoy(e)});
$('#joy').addEventListener('pointermove',e=>{if(e.pointerId!==joyPointer)return;e.preventDefault();e.stopPropagation();updateJoy(e)});
for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#joy').addEventListener(name,e=>{if(e.pointerId!==joyPointer)return;e.stopPropagation();joyPointer=null;for(const k of ['left','right','jump','drop'])mobileKeys.delete(k);$('#joy-thumb').style.transform='translate(-50%,-50%)';$('#joy').classList.remove('held')});
$('#fire-pad').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(paused||ending||settled||firePointer!==null)return;begin();firePointer=e.pointerId;$('#fire-pad').setPointerCapture(e.pointerId);$('#fire-pad').classList.add('held');updateFireAim(e);touchFire=true;updateAim();fire()});$('#fire-pad').addEventListener('pointermove',e=>{if(e.pointerId!==firePointer)return;e.preventDefault();e.stopPropagation();updateFireAim(e)});
for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#fire-pad').addEventListener(name,e=>{if(e.pointerId!==firePointer)return;e.stopPropagation();firePointer=null;fireAim=null;touchFire=stageFirePointer!==null;$('#fire-pad').classList.remove('held')});
function mobileAim(){if(firePointer===null)return false;let dx,dy;if(fireAim){dx=fireAim.dx;dy=fireAim.dy}else{const range=weapon===2?getWeaponStats().eraserRange:weapon===1?650:640,candidates=[...waveAlive(),...(level===5&&boss?.active&&boss.alive?[boss]:[])].filter(e=>e.x+e.w>=camX&&e.x<=camX+sw/scale&&e.y+e.h>=camY&&e.y<=camY+sh/scale&&Math.hypot(e.x+e.w/2-p.x,e.y+e.h/2-(p.y-24))<=range).sort((a,b)=>Math.hypot(a.x+a.w/2-p.x,a.y+a.h/2-p.y)-Math.hypot(b.x+b.w/2-p.x,b.y+b.h/2-p.y));const e=candidates[0];if(e){dx=e.x+e.w/2-p.x;dy=e.y+e.h/2-(p.y-24)}else{dx=p.face;dy=0}}
 p.angle=Math.atan2(dy,dx);p.face=Math.cos(p.angle)>=0?1:-1;cursorWorld.x=p.x+Math.cos(p.angle)*400;cursorWorld.y=p.y-24+Math.sin(p.angle)*400;return true;}
function drawWaveWarning(){if(!waves?.warning)return;const w=waves.warning,f=clamp((time-w.at)/combatConfig.warning,0,1),x=w.pos.x+41,y=w.pos.y+26;ctx.save();ctx.strokeStyle='#e48d29';ctx.fillStyle='#fff0d280';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,40,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(x,y,47,-Math.PI/2,-Math.PI/2+f*Math.PI*2);ctx.stroke();ctx.fillStyle='#a54d21';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillText('小怪即将出现',x,y-55);ctx.restore();}
